### PR TITLE
Update k8s-minio-redis example to v8

### PR DESCRIPTION
**Pull request by nachogarcia**
Update example.

### CODE REVIEW

**Comment by WoLfulus** [comment]
Hi @nachogarcia , sorry the delay. Would you mind changing the directory name to remove `old-`?

Thanks!

**Comment by nachogarcia** [comment]
It was already renamed to redis-minio @WoLfulus

**Comment by WoLfulus** [comment]
I meant the folder the files are in :)

**Comment by nachogarcia** [comment]
any updates @WoLfulus ?

**Comment by WoLfulus** [comment]
Sorry, I did check this on phone, doesn't seem like a reliable way to do it :P

**Pull request merged**
